### ISSUE TITLE
能否解决环境语言的依赖限制？

### ISSUE THREAD

**Issue by chen-ni** [yesseecity/hanlp-python#2]
我的机器是英语语言，运行example.py时确实出错了，但是我并不想只因为这个工具就更改整个系统的语言，有没有解决办法？谢谢 ：）

**Comment by yesseecity** [comment]
最新commit 的檔案中
https://github.com/yesseecity/hanlp-python/blob/master/install.sh

語系設定那邊 改成
```
sudo locale-gen es_US.UTF-8
sudo update-locale es_US.UTF-8

echo 'export LC_ALL=es_US.UTF-8' >> ~/.bashrc
echo 'export LANG=es_US.UTF-8' >> ~/.bashrc
echo 'export LANGUAGE=es_US.UTF-8' >> ~/.bashrc

source ~/.bashrc
```
這樣就可以了

重點「ascii」轉到「UTF-8」

你可以用下面的指令去看還有哪些語系可以用
```
sudo dpkg-reconfigure locales
```

我剛剛用新機器設定，這樣是可行的，你再試試看。
_________________________
可以的話，請順便Close 這個 ISSUE， 謝謝。

**Comment by chen-ni** [comment]
明白了。。其实上次安装之后语言变成中文，我自己又给改回英语了，然后运行出现错误。今天我又看了一下错误代码，**是因为我没有下载数据并放在/data 下**。。所以错误应该是和语言没有关系，但是上次我看到你在README最下面说**如果运行示例无法顺利显示结果，就改成中文**，我就还以为是因为我改成了英语所以出错呢，故有此问。

上次没把数据下下来，我再去试试。那就Close了， 谢谢 ：）
