### ISSUE TITLE
can't use the CRF segment

### ISSUE THREAD

**Issue by GlaDOSLI** [yesseecity/hanlp-python#3]
```
CRFSegment = JClass('com.hankcs.hanlp.seg.CRF.CRFSegment')             
segemntTool = CRFSegment().seg
```

SIGSEGV (0xb) at pc=0x00007faf8662e026, pid=5771, tid=5782

JRE version: Java(TM) SE Runtime Environment (10.0.1+10) (build 10.0.1+10)
Java VM: Java HotSpot(TM) 64-Bit Server VM (10.0.1+10, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
Problematic frame:
C  [_jpype.cpython-35m-x86_64-linux-gnu.so+0x45026]  JPJavaEnv::CallObjectMethod(_jobject*, _jmethodID*)+0x26

Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /home/work/nlp_summary/core.5771)

An error report file with more information is saved as:
 /home/work/nlp_summary/hs_err_pid5771.log

**Comment by yesseecity** [comment]
You can try this 
https://github.com/hankcs/pyhanlp
